#pragma once

/**
 * @file BaseObject.h
 * @brief Root base class for all UiNode-tree objects.
 *
 * Matcha equivalent of CATBaseUnknown. Provides:
 *  - MetaClass-based runtime type identification (static registration, parent chain walk)
 *  - ClassName(), IsAKindOf(name), GetMetaClass() -- all driven by MetaClass
 *  - IsA<T>() template using dynamic_cast for compile-time-safe type checking
 *  - Virtual destructor for polymorphic hierarchies
 *
 * @par MetaClass System
 * Every class in the hierarchy registers a static MetaClass instance via
 * MATCHA_DECLARE_CLASS (header) + MATCHA_IMPLEMENT_CLASS (cpp). MetaClass
 * stores the class name and a parent pointer, forming a singly-linked chain
 * from leaf to root. IsAKindOf() walks this chain -- O(depth), no hash map,
 * no dynamic_cast overhead for string-based queries.
 *
 * BaseObject is the root: its MetaClass has parent == nullptr.
 *
 * @par Ownership
 * BaseObject itself does not manage reference counting. Ownership is expressed
 * through std::unique_ptr (parent owns child) and observer_ptr / raw T*
 * (non-owning references). This follows modern C++ RAII conventions.
 */

#include "Matcha/Foundation/Macros.h"
#include "Matcha/UiNodes/Core/MetaClass.h"

#include <concepts>
#include <string_view>

namespace matcha {

/**
 * @brief Root base class for all objects in the Matcha command/UiNode hierarchy.
 *
 * Equivalent to CATBaseUnknown in the 3DEXPERIENCE architecture.
 *
 * BaseObject is the root of the MetaClass chain. Derived classes use
 * MATCHA_DECLARE_CLASS / MATCHA_IMPLEMENT_CLASS to register their MetaClass.
 * BaseObject itself has special handling: its static MetaClass has
 * parent == nullptr.
 */
class MATCHA_EXPORT BaseObject {
public:
    // -- MetaClass (root -- special: parent is nullptr) -----------------------
    static const MetaClass s_metaClass;

    [[nodiscard]] static auto GetStaticMetaClass() -> const MetaClass* {
        return &s_metaClass;
    }

    /**
     * @brief Return the MetaClass descriptor for this object's concrete type.
     *
     * Equivalent to CATBaseUnknown::GetMetaObject().
     * Override is generated by MATCHA_DECLARE_CLASS in derived classes.
     */
    [[nodiscard]] virtual auto GetMetaClass() const -> const MetaClass* {
        return &s_metaClass;
    }

    BaseObject() = default;
    virtual ~BaseObject();

    // Non-copyable, non-movable (identity-bearing object)
    BaseObject(const BaseObject&) = delete;
    auto operator=(const BaseObject&) -> BaseObject& = delete;
    BaseObject(BaseObject&&) = delete;
    auto operator=(BaseObject&&) -> BaseObject& = delete;

    /**
     * @brief Return the runtime class name of this object.
     *
     * Delegates to GetMetaClass()->name. Equivalent to CATBaseUnknown::IsA().
     */
    [[nodiscard]] virtual auto ClassName() const -> std::string_view {
        return GetMetaClass()->name;
    }

    /**
     * @brief Check whether this object is an instance of type T or a subclass.
     *
     * Uses dynamic_cast for compile-time type safety.
     */
    template <typename T>
        requires std::derived_from<T, BaseObject>
    [[nodiscard]] auto IsA() const -> bool {
        return dynamic_cast<const T*>(this) != nullptr;
    }

    /**
     * @brief Check whether this object derives from a class with the given name.
     *
     * Walks the MetaClass parent chain. O(hierarchy depth).
     * Equivalent to CATBaseUnknown::IsAKindOf(const char*).
     */
    [[nodiscard]] virtual auto IsAKindOf(std::string_view name) const -> bool {
        return GetMetaClass()->IsAKindOf(name);
    }

    /**
     * @brief Downcast to a specific derived type.
     * @tparam T Target type.
     * @return Pointer to T if the cast succeeds, nullptr otherwise.
     */
    template <typename T>
        requires std::derived_from<T, BaseObject>
    [[nodiscard]] auto As() -> T* {
        return dynamic_cast<T*>(this);
    }

    /** @brief Const overload of As(). */
    template <typename T>
        requires std::derived_from<T, BaseObject>
    [[nodiscard]] auto As() const -> const T* {
        return dynamic_cast<const T*>(this);
    }
};

} // namespace matcha
